# SVD Classifier

In [21]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt 
import time
import random
#!pip install ProgressBar
from progressbar import ProgressBar
import math
#!{sys.executable} -m pip install ProgressBar
#!pip install ProgressBar
from random import randrange
from copy import copy, deepcopy

import glob
import json

#svd stuff
from scipy.linalg import svd
from numpy.linalg import pinv


In [22]:
#load the titles and wheater the book is alive or dead into two seperate arrays
def loadResult():
    test_labels = []
    test_values = []
    with open('table-of-contents.json', encoding="utf8") as f:
        data = json.load(f)
        for books in data:
            for book in data[books]:
                test_labels.append(book['title'])
                test_values.append(book['dead'])
                
    return test_labels, test_values

#get the data from the data output file
def loadData():
    final_data = []
    with open('dataOutput2.json', encoding="utf8") as f:
        data = json.load(f)
        for index in data: 
            final_data.append(data[index]['chapData'])
    return final_data

In [23]:

                

title_labels, dead_labels = loadResult()
train = loadData()
print(len(train))
## Load the training set
train_data= np.array(train[:15705])
train_labels = np.array(dead_labels[:15705])
train_titles = np.array(title_labels[:15705])


## Load the testing set

test_data= np.array(train[-1000:])
test_labels = np.array(dead_labels[-1000:])
test_titles = np.array(title_labels[-1000:])


## Print out their dimensions
print("Training dataset dimensions: ", np.shape(train_data))
print("Number of training labels: ", len(train_labels))
print("Testing dataset dimensions: ", np.shape(test_data))
print("Number of testing labels: ", len(test_labels))



16705
Training dataset dimensions:  (15705, 71)
Number of training labels:  15705
Testing dataset dimensions:  (1000, 71)
Number of testing labels:  1000


For the next two items we are attempting to recreating the element. A should equal B


calculate pseudo inverse manually and compare to the built in version

In [24]:
#A= np.array([[0.1, 0.2],[0.3, 0.4],[0.5, 0.6],[0.7, 0.8]])
A=np.array(train_data[:])
print(A)
# calculate pseudoinverse
B = pinv(A)
print(B)

[[  0   0   0 ...   0   1  36]
 [  0   0   0 ...   0   1   7]
 [  0   0   0 ...  20  25 689]
 ...
 [  0   0   0 ...   1   0   5]
 [  0   0   0 ...   2   0   1]
 [  0   0   1 ... 187 255 232]]
[[ 1.41665154e-06 -7.87624385e-05 -1.50063288e-05 ... -8.81508881e-05
  -2.43381414e-04 -1.57186015e-04]
 [-3.11887480e-05  4.14462675e-05 -2.39004888e-04 ... -1.38122724e-04
  -1.99278900e-05 -3.38553861e-04]
 [-2.30330965e-05 -3.87923977e-05 -8.42779723e-05 ... -1.93302046e-04
  -1.29650184e-05  1.44900618e-03]
 ...
 [-3.53724560e-07  4.86100109e-07  1.05452792e-06 ...  6.99338964e-07
   5.91041688e-07 -3.66002797e-06]
 [ 4.49952314e-07 -4.67608076e-07 -1.13338360e-07 ... -6.02837625e-07
  -5.32801834e-07  3.21050947e-06]
 [-3.71539162e-09 -5.57172465e-08  5.07890139e-07 ... -1.54623509e-07
  -2.89767954e-08 -2.49413822e-07]]


In [25]:
print(A)
# calculate svd
U, s, VT = svd(A)
# reciprocals of s
d = 1.0 / s
# create m x n D matrix
D = np.zeros(A.shape)
# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = np.diag(d)
# calculate pseudoinverse
B = VT.T.dot(D.T).dot(U.T)
print(B)


[[  0   0   0 ...   0   1  36]
 [  0   0   0 ...   0   1   7]
 [  0   0   0 ...  20  25 689]
 ...
 [  0   0   0 ...   1   0   5]
 [  0   0   0 ...   2   0   1]
 [  0   0   1 ... 187 255 232]]
[[ 1.41665154e-06 -7.87624385e-05 -1.50063288e-05 ... -8.81508881e-05
  -2.43381414e-04 -1.57186015e-04]
 [-3.11883520e-05  4.14462206e-05 -2.39004961e-04 ... -1.38122710e-04
  -1.99278888e-05 -3.38553853e-04]
 [-2.30322454e-05 -3.87925141e-05 -8.42781799e-05 ... -1.93302006e-04
  -1.29647602e-05  1.44900626e-03]
 ...
 [-3.53724719e-07  4.86100125e-07  1.05452794e-06 ...  6.99338961e-07
   5.91041740e-07 -3.66002796e-06]
 [ 4.49952818e-07 -4.67608132e-07 -1.13338439e-07 ... -6.02837610e-07
  -5.32801893e-07  3.21050947e-06]
 [-3.71532570e-09 -5.57172542e-08  5.07890127e-07 ... -1.54623507e-07
  -2.89767968e-08 -2.49413821e-07]]


In [27]:
def getError(B):

    true = 0

    for i in range(len(train_data)):
        x = train_data[i]
        predict = np.sum(x.dot(B))

        #find the error
        if (train_labels[i] == False) and (predict<1):
            true +=1
        elif (train_labels[i] == True) and (predict>1):
            true+=1



        #these are  the results from the svd classification
        #print(predict, end = ": ")
        #print(train_labels[i])

        #calculate the error

    #print('error rate: ', 1-(true/len(train_data)))
    return 1-(true/len(train_data))

In [28]:
print('error rate: ', getError(B))

error rate:  0.3444126074498567


# Compute the derivative


We will now compute the derivative of the regression cost function: 
$$L_D(w) = \frac{1}{n}\sum_{i=1}^n (y_i-w\cdot x_i)^2,$$
where $x_i\in \mathrm{R}^d$ is the input feature of dimension $d$, $y_i\in\mathrm{R}$ is the output response, and $w\in\mathrm{R}^d$ is the regression weights.

**Task P3:** Complete the function 'weight_derivative' to calculate the derivative of the cost function with respect to regression weights $w$, i.e., $\frac{\partial}{\partial w}L_D(w)$. Note that this should be a $d$ dimensional vector. Also copy the output of the code for the test example to the solution file.

In [106]:
def weight_derivative(weights, feature_matrix, labels):
    # Input:
    # weights: weight vector w, a numpy vector of dimension d
    # feature_matrix: numpy array of size n by d, where n is the number of data points, and d is the feature dimension
    # labels: true labels y, a numpy vector of dimension d
    # Output:
    # Derivative of the regression cost function with respect to the weight w, a numpy array of dimension d
        
    ## STUDENT: Start of code ###
    
    sum = 0
    #get array of normalized dot produts
    dot_product=weights.dot(feature_matrix)
    #sum the diffrence between dot and true value
    for i in range(len(feature_matrix)):
        
        diffrence = labels[i] - dot_product[i]
        sum = sum + diffrence
    #finsh derive ative of regressive cost function    
    return sum/(len(feature_matrix))*2
    # End of code ###

In [107]:
# NOTE: copy the output to the solution file.



my_weights = np.zeros(len(train_data[0])) # this makes all the predictions 0
derivative = weight_derivative(my_weights, B, train_labels)

print (derivative)

1.6901408450704225


Here, we will write a function to perform gradient descent algorithm on the lineare regression cost. Given an initial point, we will update the current weights by moving in the negative gradient direction to minimize the cost function. Thus, in each iteration we obtain the updated weight $w_{t+1}$ from the current iterate $w_t$ as follows:
$$w_{t+1} = w_t - h\frac{\partial}{\partial w}L_D(w_t),$$
where $h$ is the 'step_size' that is the amount by which we move in the negative gradient direction. 

We stop when we are sufficiently close to the optimum (where gradient is the zero vector) by checking the condition with respect to the magnitude (length) of the gradient vector:
$$\|\frac{\partial}{\partial w}L_D(w_t)\|_2\leq \epsilon,$$
where $\epsilon$ is the 'tolerance' parameter.

**Task P4:** Complete the code section to perform the gradient decent in the function `regression_gradient_descent`. Copy the code to the solution file.

In [108]:
def regression_gradient_descent(feature_matrix, labels, initial_weights, step_size, tolerance):
    # Gradient descent algorithm for linear regression problem    
    
    # Input:
    # feature_matrix: numpy array of size n by d, where n is the number of data points, and d is the feature dimension
    # labels: true labels y, a numpy vector of dimension d
    # initial_weights: initial weight vector to start with, a numpy vector of dimension d
    # step_size: step size of update
    # tolerance: tolerace epsilon for stopping condition
    # Output:
    # Weights obtained after convergence
    
    converged = False 
    weights = np.array(initial_weights) # current iterate
    i = 0
    while not converged:
        i += 1
        # STUDENT: Start of code: your impelementation of what the gradient descent algorithm does in every iteration
        # Refer back to the update rule listed above: update the weight
        # Compute the gradient magnitude:
        
        weight_deriv = weight_derivative(weights[i-1], feature_matrix,labels)
        
        temp_gradient = [0]*len(weights[i-1])
        
        for a in range(len(weights[i-1])):
            weight_deriv= weight_deriv*step_size
            temp_gradient[a] =  weights[i-1][a] - weight_deriv
        gradient_magnitude = temp_gradient
        
        #size of gradient magnitude
        gradient_size = 0
        
        for a in gradient_magnitude:
            gradient_size += pow(a,2)
        gradient_size = pow(gradient_size,1/2)
        
        #reasign weights
        for j in range(len(weights[i])):
            weights[i][j]=gradient_magnitude[j]
            #weights[i][j]=temp_gradient[j]
            
        # Check the stopping condition to decide whether you want to stop the iterations
        if (gradient_size>=tolerance):             # STUDENT: check the stopping condition here
            converged = True
        if (i>=len(weights)-1):             # STUDENT: check the stopping condition here
            converged = True
        # End of code
        
        print ("Iteration: ",i,"gradient_magnitude: ", np.sum(gradient_magnitude)) # for us to check about convergence
        print('error rate: ', getError(gradient_magnitude))
        
    return gradient_magnitude

In [111]:
#STUDENT: Specify the initial_weights, step_size, and tolerance
simple_feature_matrix = B
output = train_labels



temp_weights = [np.zeros(len(train_data[0]))]# this makes all the predictions 0 #np.array([0.]*2*len(simple_feature_matrix))
temp_weights=np.array(temp_weights)
initial_weights = temp_weights.reshape(len(simple_feature_matrix),len(train_data[0]))

step_size = 0.05
tolerance = 10
# end of code

# Use the regression_gradient_descent function to calculate the gradient decent and store it in the variable 'final_weights'
final_weights = regression_gradient_descent(simple_feature_matrix, output, initial_weights, step_size, tolerance)

# end of code
print ("Here are the final weights after convergence:")
print (final_weights)

ValueError: cannot reshape array of size 71 into shape (71,71)