# SVD Classifier

revelvent infor has come so far from https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/


In [17]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt 
import time
import random
#!pip install ProgressBar
from progressbar import ProgressBar
import math
#!{sys.executable} -m pip install ProgressBar
#!pip install ProgressBar
from random import randrange
from copy import copy, deepcopy

import glob
import json

#svd stuff
from scipy.linalg import svd
from numpy.linalg import pinv


In [18]:
#load the titles and wheater the book is alive or dead into two seperate arrays
def loadResult():
    test_labels = []
    test_values = []
    with open('table-of-contents.json', encoding="utf8") as f:
        data = json.load(f)
        for books in data:
            for book in data[books]:
                test_labels.append(book['title'])
                test_values.append(book['dead'])
                
    return test_labels, test_values

#get the data from the data output file
def loadData():
    final_data = []
    with open('dataOutput2.json', encoding="utf8") as f:
        data = json.load(f)
        for index in data: 
            final_data.append(data[index]['chapData'])
    return final_data

In [19]:

                

title_labels, dead_labels = loadResult()
train = loadData()
print(len(train))
## Load the training set
train_data= np.array(train[:15705])
train_labels = np.array(dead_labels[:15705])
train_titles = np.array(title_labels[:15705])


## Load the testing set

test_data= np.array(train[-1000:])
test_labels = np.array(dead_labels[-1000:])
test_titles = np.array(title_labels[-1000:])


## Print out their dimensions
print("Training dataset dimensions: ", np.shape(train_data))
print("Number of training labels: ", len(train_labels))
print("Testing dataset dimensions: ", np.shape(test_data))
print("Number of testing labels: ", len(test_labels))



16705
Training dataset dimensions:  (15705, 71)
Number of training labels:  15705
Testing dataset dimensions:  (1000, 71)
Number of testing labels:  1000


For the next two items we are attempting to recreating the element. A should equal B


In [20]:
A = np.array(train_data)
# Singular-value decomposition
print(A)
U, s, VT = svd(A)
# create m x n Sigma matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[  0   0   0 ...   0   1  36]
 [  0   0   0 ...   0   1   7]
 [  0   0   0 ...  20  25 689]
 ...
 [  0   0   0 ...   1   0   5]
 [  0   0   0 ...   2   0   1]
 [  0   0   1 ... 187 255 232]]
[[-1.15860984e-14 -9.04811628e-12 -3.86037298e-14 ...  4.48476606e-14
   1.00000000e+00  3.60000000e+01]
 [-5.20891180e-13  4.30259198e-11 -8.45907242e-13 ...  2.05838960e-12
   1.00000000e+00  7.00000000e+00]
 [-1.07530085e-12  7.47999686e-11 -2.98695293e-13 ...  2.00000000e+01
   2.50000000e+01  6.89000000e+02]
 ...
 [-1.25027411e-12 -4.61751207e-11  3.95266928e-12 ...  1.00000000e+00
   8.22050549e-14  5.00000000e+00]
 [-1.02676857e-12  5.17274196e-11 -1.67764389e-12 ...  2.00000000e+00
   4.73449136e-14  1.00000000e+00]
 [-1.15549408e-12 -4.27149486e-11  1.00000000e+00 ...  1.87000000e+02
   2.55000000e+02  2.32000000e+02]]


In [21]:
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create n x n Sigma matrix
Sigma = np.diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[  0   0   0 ...   0   1  36]
 [  0   0   0 ...   0   1   7]
 [  0   0   0 ...  20  25 689]
 ...
 [  0   0   0 ...   1   0   5]
 [  0   0   0 ...   2   0   1]
 [  0   0   1 ... 187 255 232]]


ValueError: shapes (15705,15705) and (71,71) not aligned: 15705 (dim 1) != 71 (dim 0)

calculate pseudo inverse manually and compare to the built in version

In [22]:
print(A)
# calculate pseudoinverse
B = pinv(A)
print(B)

[[  0   0   0 ...   0   1  36]
 [  0   0   0 ...   0   1   7]
 [  0   0   0 ...  20  25 689]
 ...
 [  0   0   0 ...   1   0   5]
 [  0   0   0 ...   2   0   1]
 [  0   0   1 ... 187 255 232]]
[[ 1.41665154e-06 -7.87624385e-05 -1.50063288e-05 ... -8.81508881e-05
  -2.43381414e-04 -1.57186015e-04]
 [-3.11887480e-05  4.14462675e-05 -2.39004888e-04 ... -1.38122724e-04
  -1.99278900e-05 -3.38553861e-04]
 [-2.30330965e-05 -3.87923977e-05 -8.42779723e-05 ... -1.93302046e-04
  -1.29650184e-05  1.44900618e-03]
 ...
 [-3.53724560e-07  4.86100109e-07  1.05452792e-06 ...  6.99338964e-07
   5.91041688e-07 -3.66002797e-06]
 [ 4.49952314e-07 -4.67608076e-07 -1.13338360e-07 ... -6.02837625e-07
  -5.32801834e-07  3.21050947e-06]
 [-3.71539162e-09 -5.57172465e-08  5.07890139e-07 ... -1.54623509e-07
  -2.89767954e-08 -2.49413822e-07]]


In [24]:
print(A)
# calculate svd
U, s, VT = svd(A)
# reciprocals of s
d = 1.0 / s
# create m x n D matrix
D = np.zeros(A.shape)
# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)
# calculate pseudoinverse
B = VT.T.dot(D.T).dot(U.T)
print(B)

[[  0   0   0 ...   0   1  36]
 [  0   0   0 ...   0   1   7]
 [  0   0   0 ...  20  25 689]
 ...
 [  0   0   0 ...   1   0   5]
 [  0   0   0 ...   2   0   1]
 [  0   0   1 ... 187 255 232]]
[[ 1.41665154e-06 -7.87624385e-05 -1.50063288e-05 ... -8.81508881e-05
  -2.43381414e-04 -1.57186015e-04]
 [-3.11883520e-05  4.14462206e-05 -2.39004961e-04 ... -1.38122710e-04
  -1.99278888e-05 -3.38553853e-04]
 [-2.30322454e-05 -3.87925141e-05 -8.42781799e-05 ... -1.93302006e-04
  -1.29647602e-05  1.44900626e-03]
 ...
 [-3.53724719e-07  4.86100125e-07  1.05452794e-06 ...  6.99338961e-07
   5.91041740e-07 -3.66002796e-06]
 [ 4.49952818e-07 -4.67608132e-07 -1.13338439e-07 ... -6.02837610e-07
  -5.32801893e-07  3.21050947e-06]
 [-3.71532570e-09 -5.57172542e-08  5.07890127e-07 ... -1.54623507e-07
  -2.89767968e-08 -2.49413821e-07]]
