# SVD Classifier

revelvent infor has come so far from https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/


In [13]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt 
import time
import random
#!pip install ProgressBar
from progressbar import ProgressBar
import math
#!{sys.executable} -m pip install ProgressBar
#!pip install ProgressBar
from random import randrange
from copy import copy, deepcopy

import glob
import json

#svd stuff
from scipy.linalg import svd
from numpy.linalg import pinv


In [14]:
#load the titles and wheater the book is alive or dead into two seperate arrays
def loadResult():
    test_labels = []
    test_values = []
    with open('table-of-contents.json', encoding="utf8") as f:
        data = json.load(f)
        for books in data:
            for book in data[books]:
                test_labels.append(book['title'])
                test_values.append(book['dead'])
                
    return test_labels, test_values

#get the data from the data output file
def loadData():
    final_data = []
    with open('dataOutput2.json', encoding="utf8") as f:
        data = json.load(f)
        for index in data: 
            final_data.append(data[index]['chapData'][:-2])
    return final_data

In [15]:

                

title_labels, dead_labels = loadResult()
train = loadData()
print(len(train))
## Load the training set
train_data= np.array(train[:15705])
train_labels = np.array(dead_labels[:15705])
train_titles = np.array(title_labels[:15705])


## Load the testing set

test_data= np.array(train[-1000:])
test_labels = np.array(dead_labels[-1000:])
test_titles = np.array(title_labels[-1000:])


## Print out their dimensions
print("Training dataset dimensions: ", np.shape(train_data))
print("Number of training labels: ", len(train_labels))
print("Testing dataset dimensions: ", np.shape(test_data))
print("Number of testing labels: ", len(test_labels))



16705
Training dataset dimensions:  (15705, 69)
Number of training labels:  15705
Testing dataset dimensions:  (1000, 69)
Number of testing labels:  1000


For the next two items we are attempting to recreating the element. A should equal B


calculate pseudo inverse manually and compare to the built in version

In [16]:
#A= np.array([[0.1, 0.2],[0.3, 0.4],[0.5, 0.6],[0.7, 0.8]])
A=np.array(train_data[:][:-2])
print(A)
# calculate pseudoinverse
B = pinv(A)
print(B)

[[   0    0    0 ...  849    2    0]
 [   0    0    0 ...  336    0    0]
 [   0    0    0 ...  417   70   20]
 ...
 [   1    0    0 ... 3698  361   96]
 [   0    0    0 ...  142   13    5]
 [   0    0    0 ...  144    1    1]]
[[ 1.10539048e-06 -7.78396633e-05 -1.91528908e-05 ...  4.97438820e-04
  -2.80535040e-04 -8.64017032e-05]
 [-3.08622659e-05  4.24987368e-05 -2.50498934e-04 ... -1.72169825e-04
  -2.19158417e-04 -1.35247758e-04]
 [-2.39926333e-05 -3.70039538e-05 -9.23720359e-05 ... -1.09323794e-05
  -2.75439789e-04 -1.88112373e-04]
 ...
 [ 2.04634607e-09 -7.12583286e-09 -1.13517115e-08 ...  3.85638986e-09
   9.53456417e-09 -2.63637089e-08]
 [ 2.52959025e-08 -9.56609454e-08 -1.84438388e-07 ...  3.44069819e-07
  -1.38855558e-07 -1.34649674e-07]
 [-1.43451377e-07  3.33387678e-07  4.42646942e-07 ... -6.35014565e-07
   2.39143595e-07  5.91673585e-07]]


In [17]:
print(A)
# calculate svd
U, s, VT = svd(A)
# reciprocals of s
d = 1.0 / s
# create m x n D matrix
D = np.zeros(A.shape)
# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = np.diag(d)
# calculate pseudoinverse
B = VT.T.dot(D.T).dot(U.T)
print(B)


[[   0    0    0 ...  849    2    0]
 [   0    0    0 ...  336    0    0]
 [   0    0    0 ...  417   70   20]
 ...
 [   1    0    0 ... 3698  361   96]
 [   0    0    0 ...  142   13    5]
 [   0    0    0 ...  144    1    1]]
[[ 1.10539048e-06 -7.78396633e-05 -1.91528908e-05 ...  4.97438820e-04
  -2.80535040e-04 -8.64017032e-05]
 [-3.08626433e-05  4.24987842e-05 -2.50498858e-04 ... -1.72169833e-04
  -2.19158502e-04 -1.35247772e-04]
 [-2.39902283e-05 -3.70042778e-05 -9.23725910e-05 ... -1.09323130e-05
  -2.75438837e-04 -1.88112272e-04]
 ...
 [ 2.04636440e-09 -7.12583510e-09 -1.13517150e-08 ...  3.85639025e-09
   9.53456725e-09 -2.63637083e-08]
 [ 2.52958416e-08 -9.56609392e-08 -1.84438381e-07 ...  3.44069819e-07
  -1.38855544e-07 -1.34649675e-07]
 [-1.43451749e-07  3.33387730e-07  4.42647034e-07 ... -6.35014576e-07
   2.39143413e-07  5.91673569e-07]]


In [28]:


for i in range(len(train_data)):
    x = train_data[i]
    predict = np.sum(A.dot(x))
    
   
    
    #these are  the results from the svd classification
    #print(predict, end = ": ")
    #print(train_labels[i])
    
    #calculate the error


1926084522: True
2045305176: True
-1439299012: False
-341740963: True
19635177: True
886910820: True
160613315: True
-1058126140: True
-1309397358: True
1441435819: True
883084672: True
-519488098: True
-1424029308: True
1213635356: True
-1058507504: True
1797120328: False
-1116584688: False
825302094: True
-775477011: True
-415801893: True
-2009038147: False
1919146469: True
1326533104: False
1351826427: False
784912023: True
-674698974: True
-495887025: True
84742637: True
-1703896807: True
-1312523740: True
262018068: True
-318927917: True
440323825: True
-234084292: True
-1894241605: False
284391930: True
1169178567: True
1016281834: True
1784624790: True
-1434022931: True
-1438611094: True
-1995695590: True
472425131: True
-997409469: True
-1755436213: False
-464353344: True
-1740342869: True
2035998890: True
-1350917860: True
1333434960: True
-1990725656: True
730594661: False
36586628: True
653816717: True
1000827054: False
-405528357: True
2058518406: True
-787492076: True
-802

-1710733519: True
19691121: True
1997958752: True
-2019544889: False
1830824920: True
-1452706962: True
-1442415566: True
-1934660647: True
-1883546929: True
-1907284543: True
-181798613: True
506408445: True
-151345026: True
-1521016597: True
1290400860: True
1330065671: True
1088092314: True
2084524809: True
-1598873564: True
2144624708: True
320895462: True
-462135965: True
48618382: True
794671157: True
-832109869: True
990499202: True
26760244: True
-799242791: True
-1357385439: True
463133962: True
-1327580351: True
-587416291: False
885702153: True
2013399192: False
-526503301: True
-1100687847: True
1318073202: False
-1725200718: True
-2008942012: True
1945488579: True
1859864591: True
746285273: True
-902179236: True
-1937268123: True
33480257: True
1681538369: False
114529078: True
684310248: True
-233197282: True
-499398498: True
1495193299: True
57373642: True
797576143: True
158360531: True
872632652: True
1389703096: True
1438157702: False
-718397806: True
-2036582693: Tr

1661686099: True
1804070444: True
1618623351: True
936993489: True
-5848467: True
1089446731: True
-100668354: True
1822067791: True
-134912049: False
2081495741: True
1040175281: True
-262934031: False
893693793: True
1270503704: True
1934619242: True
1194144521: False
310858672: False
-1496394395: True
1044897757: True
1787796981: True
1920359028: True
115001724: True
-848912598: True
847290609: True
732031077: False
2002992093: True
1572327687: True
739429476: True
1424829966: True
-1114842868: True
-434702472: True
165903565: True
1207483463: True
893342225: True
1110053039: True
-593856596: False
-59411170: True
-255617825: True
-579909580: True
763819979: False
-938767941: False
168365298: True
1343305829: True
-1664025782: False
-1847834282: True
-1521580156: True
1065160847: True
-804050420: True
-174286394: False
1536921728: True
-952117465: True
-68376377: True
2100393759: True
1351864773: True
-1385006812: True
-1117934935: True
1522592562: False
-646470637: True
-1532374733

475516480: False
1045198963: True
2090515909: True
1511687961: True
845018743: True
652068995: True
58934471: False
-912052176: False
-148610597: True
-1201611283: True
907804199: True
-302677815: True
965022020: True
-119591282: True
1134233245: True
37482407: True
1984440007: False
651096579: False
-678060640: True
1721372690: True
-1997085424: True
1371759908: True
1164805515: True
1426181364: True
1933674647: True
1245799840: True
-1075332392: True
-1810805713: True
-913549932: False
351536406: True
-1643123404: True
2017681474: True
-615669516: True
69332970: True
-109980455: True
354176281: True
-1313535116: True
333012893: True
-1774118038: True
543773633: True
-159956299: True
-1443174915: True
1957703164: True
1040095356: True
741536006: True
266404298: True
-441901645: False
1701242300: True
1962457434: True
1432170282: True
-2030222970: True
-2131533960: True
-239525721: True
-519591948: True
1700541149: True
-1558199269: False
-1488483344: True
1500799455: True
1665656777: 

307049288: False
-1989953136: True
876621677: True
-626399267: True
1972408770: True
-1474889600: True
1977094131: True
1411126593: True
1481092304: True
574475766: True
-1939121676: False
-1165596687: True
1845208593: True
1105732153: True
-1001644676: True
-492122052: False
808858676: True
1597568538: True
-134100751: True
254742346: True
-95258785: True
1804402025: True
-1614886473: True
1261826704: True
-1499561205: True
-796158417: True
-1559618108: True
-1249190939: True
-94793689: True
413316719: True
1220838925: True
-1557909688: True
-1176304145: True
335255053: True
1113890463: True
-410284942: True
863525716: True
56142771: True
223105285: True
-2128640020: True
-908928704: True
444392141: True
-294321888: True
-379660496: True
-1484900665: True
167377620: True
1360617052: True
1061049518: False
-578641789: True
579127426: True
823908856: True
-1720217566: True
-2120150028: True
-343790319: True
-1210975948: True
538175676: True
-356479765: True
1908037279: True
-2112897040:

-2075386596: True
-1847133363: True
-1382846216: True
-669066679: True
-2097667624: True
379551689: True
-292454957: False
-2069377441: False
1252054479: True
348912549: True
-2060693247: True
-804753705: False
249073674: True
1978857326: True
-889600395: True
-1929051786: True
-969864521: True
-1142769599: False
154840148: True
-1198780803: True
994873188: True
1143968306: True
-356803722: True
713967452: True
-1116662407: True
-406993979: True
-842425780: True
768701434: False
-884920969: True
235163389: False
775678180: True
16486264: True
-544094586: False
2113706361: False
675107389: False
-203854298: False
438611018: True
1169631832: True
1043430580: True
433133084: True
1984839975: True
1617221012: True
-251080745: True
32491812: True
-1696032421: True
1975439054: False
1818105935: False
-149584315: True
-638504683: True
117894070: False
1213264557: True
96193220: False
-1541515821: True
1560052384: True
562327683: True
-1396877030: True
611648127: True
-1069444872: False
-19901

-1834079821: True
664745628: True
-1519398263: True
-1694347857: True
-1677131926: True
-313231601: True
-1220564117: True
-740874771: True
-108366824: True
-291801683: False
-1541442515: True
-1155376662: True
236922301: True
325624192: True
1103825959: True
427317298: True
1824201213: False
-1388280993: True
-1865433337: True
1568742800: True
-672150137: True
-1057981158: True
19892954: True
45437752: True
-542430133: True
941454254: True
-1642641542: True
834392176: True
259238132: True
-100174842: True
-1026180040: True
1614107711: True
945725323: True
981866837: True
741509564: True
-2036465320: True
72508962: True
218406500: True
2025472587: True
535310449: True
424115866: True
-495202298: True
-1340030964: True
-67124377: True
1210209433: True
-1428567631: False
2027171521: False
-1256785024: True
1183485192: False
1662055938: True
1504663078: True
1951101022: True
1005672203: True
-1125411093: True
-1659043087: True
-262703760: True
137543480: False
645831055: True
1036918122: 

1800281868: True
1569023394: True
-1744813537: True
-927824744: True
1384326379: True
1157369043: True
-971102282: True
-594343543: True
1465640856: True
1599576070: True
-133434447: True
-1843553722: True
-1755373029: True
1627377842: True
2068058492: True
1150229301: True
1863489090: True
-1885053897: True
2038357994: True
-312112378: True
472570296: True
-1109656980: True
-1050201036: True
-1210518560: True
-390868495: False
767697157: True
2114720620: True
-888843262: True
-373250420: True
1836390721: True
1180497872: True
-729929611: True
2055253063: True
2127555873: True
-811978429: True
-1184107426: True
1487758012: True
1958142877: True
431641400: True
-1847669314: True
-636605415: True
-1674229280: True
868167721: True
-213736316: True
1323642109: True
-1138538455: True
1718803504: True
636234623: False
1066796394: True
-1303465361: False
606698875: True
-1916804852: False
-488149873: True
-1349903687: True
-1438382900: True
1993846472: True
781446031: True
-107837162: True
55

-306330260: True
-1520002821: True
1483256904: True
-1788610416: False
1391206041: True
-1690085822: True
283365526: True
990545523: True
1386995219: False
-1090723857: True
1555819597: True
443862851: False
375429139: True
1897667363: True
-1385061586: True
1526119907: True
-22471888: True
-1649528869: True
947476760: True
1840637685: False
-2099521739: True
-1125613477: True
-1934905241: True
-1990917840: True
-1623897595: True
495243424: False
-2081382141: True
-2034358485: True
1337840410: True
-199694417: True
-1464054430: True
-458535152: True
-521947782: True
-1066689342: True
-634312520: True
178507336: True
-848508436: True
1150412231: True
150766029: True
-1336809984: True
-396662772: False
1647434531: True
1634375123: True
1230658622: True
-510801055: True
-2133080900: True
-1231411497: True
-99024371: True
1247882377: True
-1460214869: True
995913335: True
-807573426: True
-2142819525: False
1044435498: True
-702207801: True
-845453095: True
-731748422: True
1478283553: Tru

-805901715: True
664734194: True
-1895978675: True
-630626196: True
325483285: True
-267008328: True
848744495: True
-138323625: True
-1772731550: True
-555377554: True
1800132295: True
-926333587: True
796111726: True
-419165687: True
-516780125: True
325046879: True
1376941764: True
-2085509613: True
-338070434: True
-39869695: True
-791160019: True
-527962774: True
1785921234: True
2136816620: True
569476219: True
-735106813: True
-996805007: True
-171884272: True
1774652317: True
2060572342: True
-57485555: True
-672953111: False
-1145646094: False
379300635: True
-2039126057: True
1878665739: True
1495272468: True
1069605351: True
-1698453342: True
696189550: True
-812810693: True
1764043923: True
1090118758: True
1429092214: True
-1435267359: True
1464829610: True
-533433536: True
-698883489: True
1666153965: True
1255224712: True
345110093: True
-1095625700: True
-2024481808: True
1048788800: True
508113527: True
1438552488: True
-1410072562: True
915989534: True
-188171167: Tru

2095130392: True
1778404881: True
2127038453: True
-1618137447: False
-165080525: True
-1091814990: False
-952076940: True
-2101492435: True
-1397180913: True
894291352: True
-742631875: True
-373406934: True
798005923: True
500752521: True
1181157531: True
-1213782745: True
-1259486907: True
1180607302: True
-274575829: True
-1507555734: True
-414823116: True
1625813262: True
-422871482: True
-70896551: True
343365870: True
533762187: True
-932182772: True
673735074: True
-663148874: True
1835447804: True
1500462365: True
-1513393207: True
641044890: True
-837287073: False
1294397717: False
-1050670160: True
1213497816: True
170273751: True
-376032251: True
-1350652253: True
-382617658: True
-1893105731: True
1429989400: True
-694612318: False
-858540180: True
873387901: True
-149043273: True
-1338284101: True
972355068: True
438607851: True
568389134: True
-1129988406: True
-2001030562: True
-348398537: True
1498262713: True
1320159249: False
-366106317: True
-1647472459: True
738187

-1086692513: True
1633679423: True
819486787: True
-2112348335: True
-225095537: True
-1356246165: True
592377012: True
1696559913: True
753245012: True
-1877389345: True
-587685572: True
-853556930: False
-1724876858: True
-284482870: True
-286301769: False
-1220580534: True
-565440672: True
-2136590087: True
-312795951: True
-1124870478: True
-1851014041: True
995921552: True
650634664: True
1945892897: False
477608611: True
934526769: True
2130005737: True
1371356531: True
-47820793: True
-586178519: True
-2019116682: True
-1197726992: True
-99876549: True
1590457177: True
-1930349651: True
1330396066: True
1137968978: True
-1500836372: True
920493683: True
748023620: True
407776456: True
-317789143: True
-1308284752: True
150742645: False
-912327470: True
-1596314552: True
923853764: True
1419234831: True
-1468553604: True
1619157856: True
-1641067142: True
-2034031229: False
-1935389651: True
-328167692: True
1665756830: True
-1463943732: False
1268985317: True
1198347926: True
14

2035531917: True
1449769258: True
-2053032431: True
786727552: True
-2106555796: True
1277251394: True
1713090934: True
-915380683: False
-1349162504: True
-1935238817: True
2034548462: True
-515266404: True
1469061303: True
-1534689674: True
-218436576: True
1903681195: True
1644463933: True
-1443322387: True
-1112975941: True
448379862: True
-2052104496: True
-1645016464: False
1600687020: True
-1022756247: True
-1588278183: True
44016439: True
851444395: True
129432550: False
-2034570062: True
-1377503388: True
1904780004: True
-72819012: True
1018627986: True
912640555: True
-1193639010: True
1058390502: True
320524090: True
-60739071: True
182564333: True
-14834476: False
527908392: True
-387503665: True
-2071608916: True
-1701443334: True
1900369318: True
-1987291168: True
-1762507004: True
1882234405: True
-953617061: True
-1950549942: True
-2018820069: True
-725932993: True
39852684: True
1090474741: True
-33504082: True
1000536828: True
-813196701: True
718420193: True
-123387

-1476122993: True
786275414: True
1149824762: True
-712507102: True
1012066697: True
1783062371: True
-439259046: False
-721059684: True
176074216: True
-461007782: True
-1690988204: False
1512646723: True
650148604: True
-329045287: True
-623703388: True
1936920490: True
350318754: True
-809075253: True
361650371: True
-34891386: True
-446020160: True
-225884671: True
1502873002: True
-1521224551: True
848169452: True
-275823123: True
1163770608: True
1251167413: True
1146659182: True
-621023180: True
-256709886: True
-1170015357: False
-1420729662: True
807373385: False
-462272731: True
-1891523914: True
-440741573: True
-115409031: True
1290379822: True
1001840867: True
-851395027: True
-690923957: True
293552511: True
-134472: False
328176685: True
1789386253: False
195129721: True
-239717293: True
1871388715: True
-1053703408: True
2041043241: True
1713969951: True
-2016498156: False
-537909094: True
-321552186: False
1095285665: False
-1371412981: True
1465147416: True
759650293:

-716391627: True
55205199: True
1792263067: False
-2010073525: True
-2122614925: True
-1242582475: True
121939167: True
813873450: True
-1625200967: True
-1354464583: True
1377961056: True
1709059836: True
1122983479: True
-1097448737: True
-1013389068: True
-2021110372: True
1988430497: True
562440810: True
2078090321: False
-2029882051: True
988743393: False
-409432376: True
-244080249: True
110034600: True
-1093257931: True
1749522221: True
-641895757: True
-2019660182: True
-583909503: True
2048726621: False
558885555: False
-557885443: True
140447135: True
-1245305933: True
374526639: False
1876067080: True
-307377422: True
-1270195691: True
-1648340048: True
1135530150: True
912520054: True
1864362011: False
1576923117: True
150826627: True
2027085225: True
-1813386306: True
31717348: True
-982732295: True
1425913239: True
1107222565: False
291810584: True
-557481760: True
-1984962551: True
-1380319276: True
-1537126093: True
-1825163369: True
943580370: True
631642349: True
-104

2049779846: True
-688827219: False
1073475370: False
676485401: True
-554843602: True
447385893: True
-103919121: True
-1190635835: True
-1822283445: True
195695492: True
-398031301: True
58565053: True
1737381962: True
-402848010: True
-1996756149: True
-1361981696: True
1305696292: True
-1754575824: True
346581723: True
656527718: True
-859876239: True
1959969746: True
-778849041: True
1014514539: False
-1035163364: True
1786305213: True
586679199: True
1916993745: True
-1183896865: True
-1790984052: True
1588707178: True
1594557355: False
-226951966: False
314203861: True
-1974588112: True
184749748: True
1521733261: True
613273310: True
1088866625: True
307928365: True
1402715762: True
-1152945979: True
-1648442316: True
380279308: True
738544399: True
-1886254349: False
-961803296: False
-2078543402: True
318529658: True
-1058907090: True
-1650813449: True
-442411381: True
533817862: True
-2106228549: True
312401313: True
-1435812572: True
131198864: True
-237785025: True
-8655225

-178110696: False
1252522194: True
1476264549: True
-1048408202: True
1988570376: True
-1410366866: True
733641920: True
1007648818: True
1969926277: True
1800961676: True
-8487410: True
-630451772: True
1135674158: True
665554901: True
508247189: True
2067583318: True
-1747406144: True
-444043816: True
-1484263741: True
-1632263752: True
96341598: False
1771226485: True
1740483203: True
1148436390: True
1324098041: True
1487493927: True
-2130695844: True
2085779913: True
-980736283: False
1677888815: False
-377015742: True
-1457956115: True
-1939526902: True
346132896: True
1425640425: True
2023094182: True
-184978123: True
-408630484: True
538619129: False
-1059830684: True
971125412: True
796498839: True
-881204513: True
1592854131: False
-1287934834: True
-729922151: True
-289838157: True
1912304432: True
776884418: True
910315072: True
-518878153: True
-906581222: True
-1009591394: True
2086224374: True
1628005139: True
-2111268961: False
1018407555: True
415606307: True
-12871577

-941918477: False
-1096946705: False
-317314236: True
246288578: True
-1365066297: True
70335657: True
1129504097: False
2049039083: False
706846257: True
-286207562: True
-1799840576: True
-731709076: True
-943241353: True
496397983: True
418546241: False
2099766427: True
-2043015985: True
-307354372: True
-404543479: True
338687654: True
-154708462: True
-510817605: True
-650533934: True
-729206870: True
-1215560509: True
-1835769492: True
691864523: True
-1157168803: True
-953728089: True
770767743: True
-1785650293: True
-1265778072: True
145566576: True
-731724706: True
-637607697: True
261578408: True
1874189670: True
-1828609433: True
1251040222: True
-9034402: True
1284046493: True
1864103943: True
-1622563844: True
63347431: True
-271215217: True
1905249089: True
1295066365: True
1947261908: True
-1027426229: True
-3054015: True
1115654375: True
2101270730: True
1442630166: True
2067319189: True
488246120: True
-2132565354: True
1160125649: True
1346419761: False
457690098: Tr

-1235132614: False
2006671418: True
297308230: False
-153130656: True
1026433663: True
736038436: True
1003787702: True
304905369: True
2081512080: True
868474530: True
-1718222997: True
-1431709083: True
-185250760: True
-649145477: True
1240344989: True
109760913: True
1483325052: True
2112317304: True
-14324818: True
-1030183630: True
-927352468: True
-1475579396: False
1414166543: True
-1663676254: True
406985335: True
-1520682376: True
-1590807655: True
-955294724: True
1588885017: True
-2096688295: True
830857986: True
-830615549: True
133012840: True
1687760008: True
966513542: True
-2063721544: True
1278376968: True
356314309: True
433955301: True
-1203911458: True
-942395064: True
-1184424285: True
-832587716: True
221763260: True
1657247013: True
105045109: True
-1384133523: True
2125898604: True
2061649592: True
491548934: True
-1699423011: True
1922109199: True
1175560736: True
-1442600446: True
100900932: True
1351826890: True
-911421764: True
-745887731: True
1318963611: 

538588396: True
-713336903: True
-444302036: True
-1504619445: False
212086428: False
-287947719: True
-1874704810: True
-1200248643: True
-917691233: True
-1733084286: True
1090783249: True
2105390136: True
983691780: True
-632769292: False
1394635312: True
1318627488: True
1481646839: True
-1851290607: True
-2103192810: True
-1491868733: True
-1243884868: True
1101617446: False
471921520: True
-1943204550: True
-2012454054: True
-712949262: True
613498811: True
-809764498: False
711246212: True
1855448504: True
1684068969: True
-1611975668: True
-1726434968: True
1467019530: True
-1171603960: False
840123712: False
804198948: True
-1240797294: True
1127776690: True
1407464061: True
-552833512: True
-1182229623: True
-1805861926: True
2091131709: True
1166264459: False
644540641: True
1956817695: True
-1148686750: True
1678375194: False
1742990537: True
245152285: True
-198816907: False
-1127854332: False
-2139477992: True
2010758323: True
299179060: True
-1319816701: True
904941961: 

1756879579: True
1316968122: True
-1806743457: True
683537973: True
1065477642: True
1661128759: True
-1930420310: True
873722439: True
-1998169266: True
15840224: True
-48550542: True
1059801900: True
747394080: True
-1985581118: True
-840201538: True
282741060: True
-1641970077: True
-859702291: True
2033895599: True
1534768146: False
-1048826040: True
1519140951: True
-2132115030: False
1194421981: True
-437803333: True
1132336279: False
-2042313312: True
-1917776313: True
-1254482870: True
-1518746928: True
219555192: False
-545907689: True
-830208628: True
2063378612: True
573105228: True
-82261067: False
-103171473: True
-1936665279: True
612347527: True
976610482: True
2039133716: True
1959920224: True
1458235419: False
1539761641: True
-1797110848: True
1106289402: True
-734189935: True
1050384750: True
1842519330: False
-1018967940: True
-1325683546: True
90469876: True
553060697: True
-1152834719: True
-1453275700: True
-536673646: True
-1818122949: True
33514577: True
-50774

324628061: False
-1226109938: True
49852394: True
589456671: False
-752105567: False
-1679364776: True
1578233651: True
-189350321: False
1885361993: True
-1180928466: True
673706918: True
-221121255: True
-1208671988: True
1397614555: True
-786154731: True
980153993: True
-62162832: True
529089965: True
1317729663: True
1981174820: True
-1409106631: True
-1881175239: True
-847015069: True
-1692595810: True
-1287939246: True
-473759177: True
-27847909: True
-689987755: True
-1426636788: True
442890127: False
-812434047: False
2111855982: True
445608208: True
-2117064599: True
-2134846360: False
206214791: True
1524080149: True
77098102: True
-1953324024: False
-318406071: True
-1231181555: True
976599740: True
1598438984: True
1858209215: True
-221361085: True
13739011: True
127332282: False
372239362: True
-108730929: True
-1883330342: True
302982471: True
566977740: True
-1686404965: True
1041442510: False
754858616: True
2011992042: True
-595615381: True
358784585: True
-1145841622:

1850444466: True
1603447919: True
-22926372: True
203634880: True
1351836494: False
178675546: True
-1413983582: True
2136060821: True
2045505828: True
1966191670: True
-2025340465: True
1946712383: True
1945792710: True
-1606749394: True
553444228: True
107018700: True
1133624665: True
-307353439: True
-813723041: True
1911667851: True
1164341683: True
2144727846: True
1000373245: True
1817909981: True
1276092703: True
768681922: True
-1097919939: True
-794267632: True
-759879346: True
-989506993: True
634853106: True
-1992277228: True
2076877619: True
-843026109: True
-630450078: True
2111940738: True
1605077097: True
-2014174075: True
29620165: True
103238880: True
1654754075: True
-2077797922: True
1732915967: True
-581977422: True
1763923372: True
-673045264: True
1345511177: True
-736390295: True
787528749: True
-2041853006: False
-134318501: True
-2124165560: False
1262066249: True
-1738634366: True
-1898202702: False
989901653: True
-436990671: True
-2072183891: True
1983844335

1388653722: True
-2114592509: True
-221394219: True
-256808544: True
-1692624459: True
1413715214: True
1463397604: True
939504969: True
-1840785898: True
-670295269: True
558796534: True
116605019: True
-277618403: True
-631741041: False
1263076493: True
1088149224: True
-994304880: True
-319304390: True
2125162080: True
-1649286124: False
760681051: True
886916845: True
1728058052: True
1445844828: True
316951063: True
-582844449: True
521227895: True
-1573418822: True
-1006670030: True
1749273608: True
1908053717: True
1878487598: True
1508263231: True
197945370: True
370784856: True
-364147942: True
-1611633032: True
861208728: True
5815416: True
-1435951209: True
-107533536: True
908799880: True
1139874710: True
-922844649: True
-1363825389: True
-384320659: True
1084158472: True
-406088169: True
-1045024188: True
-2129576777: True
-552308749: True
-1833321550: False
1687316131: True
-619191698: True
-1490498560: False
-1464656421: True
-985512414: True
-1340908396: True
-11550657

-828079854: True
-1523077296: True
1787099948: True
207784868: True
-702252610: True
1438243851: False
1995402789: True
-920750982: True
-545216324: True
1079215934: True
1290578643: True
1694366931: True
-2056157699: True
2037361679: False
-405767933: True
-124966460: True
-1897040829: True
1128167227: True
154574240: True
1997312538: True
-1722212312: False
1504894268: True
-337206347: True
-414264536: True
-568437002: True
1889065309: True
-1543357530: False
379343740: False
1068517828: True
-179707875: True
-777044470: True
-2081696465: True
518821803: True
-1050367598: True
-1151019528: True
-1188980335: False
935874357: True
-668596780: True
1796968534: True
-1755275522: False
-74681992: True
-1617934183: True
352802017: True
-1979507039: True
2129033691: True
725566361: True
987991980: True
-1379046007: True
1825206135: True
1956818090: True
1694047436: True
-1627956390: True
-977256052: True
-1819827542: True
1787772860: False
-1948397802: True
-1787772167: True
1176765545: Tru

-426413981: True
-745858284: True
2000205579: True
488857525: True
-1656756275: True
170881133: True
788500479: True
-974168296: True
1240597339: True
1222547498: True
1310072429: True
-1570142477: True
-1815371115: True
-1866134672: True
97034369: True
-1688696647: True
1601855099: True
27872995: True
-1433337142: True
-763913147: True
1135492094: True
-1328971895: True
-1275823235: False
-1928453904: True
1933161624: False
260971893: True
-2003856928: False
-308343482: True
-918822816: True
785032285: True
845725627: False
336956498: False
-666528926: True
1962272769: True
-983656322: True
-1499834963: True
17234002: True
1423019248: True
-1452190118: True
-1267035646: True
-1997301951: False
-46131570: False
-435545821: True
-1815160314: True
-1800973318: True
21838141: False
853880368: False
662699318: True
914137818: True
-1161809116: False
1203378993: True
1245854529: True
654068399: True
-320171521: True
1893747997: True
957610118: True
-1283400040: True
-987541364: True
-100785

1381888369: True
-1441966013: True
-618236200: True
1532174452: True
795849143: True
2061652616: True
-758857553: True
711495841: True
716407834: True
-492631318: True
-424236976: True
-1637051523: True
235490423: True
-1318130488: True
-1564095605: True
-754913501: False
1041557384: True
204901577: True
-765778136: False
1848280582: True
103753597: True
-1333830906: True
-637955215: True
1793437218: True
1607472432: True
-42234715: True
1519134095: True
194094779: False
-586736790: True
1130430270: True
59604409: False
1350247493: True
509390442: True
681756101: True
1534060525: True
1135238503: True
-1528032630: True
-1822376719: True
680848283: True
95406475: True
-1974114127: True
-432499627: False
-1752742185: True
-1681606413: True
1381701756: False
-967665906: True
-2132097875: True
2086805058: True
1005115683: True
-1768699309: True
-1964400142: True
1726095673: True
-1082399154: True
330835001: True
1149618302: True
169601446: True
506457799: True
-1532328379: True
545169243: 

607873274: True
-1130401294: True
-804129501: True
1559193877: True
-1803079100: True
-281830081: True
-213009857: True
-1929403671: True
-570950895: True
126695474: True
1200505273: True
1629143810: True
1926040568: True
1486356081: True
1625578046: True
21348175: True
2027775434: True
1849200349: True
2129434242: True
564685792: True
-1605202185: True
2043864371: True
1247879246: True
1404723114: False
-232547034: True
-518853426: True
1932603265: True
-460038862: True
-1518395418: False
-307239737: True
-851679292: True
1323882501: False
1424909041: False
730223986: True
1718061482: True
-1385630148: False
-1752260673: True
1342780333: True
-1094577626: True
-154599528: True
331781660: True
-873894875: True
-1228537252: True
1517794146: True
2088608393: True
1665534809: True
-1138870292: True
-1824814604: True
-2058622750: True
-487522033: True
-1753635956: True
-1932468081: True
-78316206: True
1031303087: True
-1291949745: True
-1952415773: True
-6149591: True
-1452207845: False
4

544668791: True
-1256763136: True
1538014896: True
-582913015: True
-1202570039: True
692701725: True
177078892: True
1370073832: True
-964359064: True
646194265: True
1756399761: True
-26536116: True
-1075343575: True
-686821790: True
1515312122: True
-171238498: True
-2040251513: True
538044226: True
-357093106: True
-1682052733: True
146732439: True
-909394740: True
1257016235: True
-1415494197: True
1845956529: False
-521077785: True
514392822: True
484545255: True
-2005639133: True
1961302040: True
-2007276068: True
1719950416: True
-2143588595: True
53267907: True
1058163851: True
-443474527: True
-207140978: True
1957168406: True
-40184600: True
493253571: False
687556952: True
2015746005: True
1856005619: True
-2011853443: True
1912785003: True
-1892199954: True
1420900380: False
-1393039418: True
634377123: True
1844821775: True
1560679522: True
-696088412: True
-738237826: True
-407332066: True
2135651537: True
2131174525: False
-1147940143: True
1454834532: True
1307965941: 

788741553: True
1534199432: True
-1387368525: True
-1086059904: True
1726366295: True
262220035: True
903043186: True
-1226037206: True
1479826238: True
755189830: True
-341493173: False
941204595: True
506457045: True
-593026620: True
1832533135: True
1362798284: True
-1887108356: True
-1047922442: True
-1827710690: True
608173497: True
1331025505: True
-1595616289: True
-603264392: True
-1479724906: False
1666669327: False
509066594: True
1407473747: True
153600660: True
899234148: True
2013058514: True
597775524: True
-1899268877: True
-1713793800: False
1623627006: False
571465908: True
-496725553: True
-1523972709: True
-1314031517: False
554679937: True
-1229354447: True
1051808388: True
214884766: True
1984451361: True
-1271826101: True
-234810574: True
1827212981: True
-969571972: True
-1430381162: True
-62524760: True
543448634: True
-1792459468: False
-64987221: True
-1233430650: True
-1943399399: True
1361627084: True
1619863330: True
15191736: True
1126853352: True
73493128

2053679788: True
-256519615: True
-1885176316: True
-100388163: True
2101817632: True
1847616118: True
-1460550374: True
1307816495: True
-34078495: True
219486675: False
1146534061: False
-1423759591: True
-1831536784: True
1525032914: True
-476657738: True
-60176582: True
-989353512: True
-2066365574: True
695702174: False
-2098538829: True
147064887: True
1466445458: True
-141489615: True
1347673100: True
-1672033790: True
-1949819156: True
197851462: False
1321972401: True
-1539940391: True
1543612873: True
-958827767: True
-59608398: True
596337866: True
1461178503: False
-1605853247: True
-1297519570: True
1121949568: True
951084865: False
-738942039: True
-1368441293: True
-79568564: True
-216613459: True
1410344201: True
1397956136: True
29870302: True
-1661811545: True
709084900: True
669280385: True
124212303: True
470262680: True
135194613: True
1605057202: True
415338958: False
716297884: True
-1067517372: True
90144805: True
1348171139: True
-949282426: True
-905244319: Fa